volumes:
  db_data:
  redis_data:

services:
  db:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-invoiceshelf}
      MYSQL_USER: ${DB_USERNAME:-invoiceshelf}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: redis
    volumes:
      - redis_data:/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    environment:
      APP_ENV: ${APP_ENV:-production}
      APP_KEY: ${APP_KEY}
      APP_DEBUG: ${APP_DEBUG:-false}
      APP_LOG_LEVEL: ${APP_LOG_LEVEL:-error}
      APP_URL: ${APP_URL:-http://invoiceshelf.test}
      DB_CONNECTION: ${DB_CONNECTION:-mysql}
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: ${DB_PORT:-3306}
      DB_DATABASE: ${DB_DATABASE:-invoiceshelf}
      DB_USERNAME: ${DB_USERNAME:-invoiceshelf}
      DB_PASSWORD: ${DB_PASSWORD}
      BROADCAST_DRIVER: ${BROADCAST_DRIVER:-log}
      CACHE_DRIVER: ${CACHE_DRIVER:-redis}
      QUEUE_DRIVER: ${QUEUE_DRIVER:-redis}
      SESSION_DRIVER: ${SESSION_DRIVER:-redis}
      SESSION_LIFETIME: ${SESSION_LIFETIME:-1440}
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PASSWORD: ${REDIS_PASSWORD:-null}
      REDIS_PORT: ${REDIS_PORT:-6379}
      MAIL_DRIVER: ${MAIL_DRIVER:-mailgun}
      MAILGUN_DOMAIN: ${MAILGUN_DOMAIN:-mg.srvxx.com}
      MAILGUN_SECRET: ${MAILGUN_SECRET}
      MAIL_HOST: ${MAIL_HOST:-smtp.mailgun.org}
      MAIL_PORT: ${MAIL_PORT:-587}
      MAIL_USERNAME: ${MAIL_USERNAME:-invoiceshelf@mg.srvxx.com}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_ENCRYPTION: ${MAIL_ENCRYPTION:-tls}
      PUSHER_APP_ID: ${PUSHER_APP_ID:-null}
      PUSHER_KEY: ${PUSHER_KEY:-null}
      PUSHER_SECRET: ${PUSHER_SECRET:-null}
      SANCTUM_STATEFUL_DOMAINS: ${SANCTUM_STATEFUL_DOMAINS:-invoiceshelf.test}
      SENTRY_LARAVEL_DSN: ${SENTRY_LARAVEL_DSN:-null}
      SESSION_DOMAIN: ${SESSION_DOMAIN:-invoiceshelf.test}
      TRUSTED_PROXIES: ${TRUSTED_PROXIES:-*}
    volumes:
      - ./storage:/var/www/storage
      - ./bootstrap/cache:/var/www/bootstrap/cache
    depends_on:
      - db
      - redis
    ports:
      - "8000:8080"

  horizon:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: horizon
    command: php artisan horizon
    environment:
      APP_ENV: ${APP_ENV:-production}
      APP_KEY: ${APP_KEY}
      APP_DEBUG: ${APP_DEBUG:-false}
      APP_LOG_LEVEL: ${APP_LOG_LEVEL:-error}
      APP_URL: ${APP_URL:-http://invoiceshelf.test}
      DB_CONNECTION: ${DB_CONNECTION:-mysql}
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: ${DB_PORT:-3306}
      DB_DATABASE: ${DB_DATABASE:-invoiceshelf}
      DB_USERNAME: ${DB_USERNAME:-invoiceshelf}
      DB_PASSWORD: ${DB_PASSWORD}
      BROADCAST_DRIVER: ${BROADCAST_DRIVER:-log}
      CACHE_DRIVER: ${CACHE_DRIVER:-redis}
      QUEUE_DRIVER: ${QUEUE_DRIVER:-redis}
      SESSION_DRIVER: ${SESSION_DRIVER:-redis}
      SESSION_LIFETIME: ${SESSION_LIFETIME:-1440}
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PASSWORD: ${REDIS_PASSWORD:-null}
      REDIS_PORT: ${REDIS_PORT:-6379}
      MAIL_DRIVER: ${MAIL_DRIVER:-mailgun}
      MAILGUN_DOMAIN: ${MAILGUN_DOMAIN:-mg.srvxx.com}
      MAILGUN_SECRET: ${MAILGUN_SECRET}
      MAIL_HOST: ${MAIL_HOST:-smtp.mailgun.org}
      MAIL_PORT: ${MAIL_PORT:-587}
      MAIL_USERNAME: ${MAIL_USERNAME:-invoiceshelf@mg.srvxx.com}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_ENCRYPTION: ${MAIL_ENCRYPTION:-tls}
      PUSHER_APP_ID: ${PUSHER_APP_ID:-null}
      PUSHER_KEY: ${PUSHER_KEY:-null}
      PUSHER_SECRET: ${PUSHER_SECRET:-null}
      SANCTUM_STATEFUL_DOMAINS: ${SANCTUM_STATEFUL_DOMAINS:-invoiceshelf.test}
      SENTRY_LARAVEL_DSN: ${SENTRY_LARAVEL_DSN:-null}
      SESSION_DOMAIN: ${SESSION_DOMAIN:-invoiceshelf.test}
      TRUSTED_PROXIES: ${TRUSTED_PROXIES:-*}
    depends_on:
      - redis
      - db
    ports:
      - "8001:8080"

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scheduler
    command: |
      sh -c "while [ true ]; do php artisan schedule:run --no-interaction --quiet; sleep 60; done"
    environment:
      APP_ENV: ${APP_ENV:-production}
      APP_KEY: ${APP_KEY}
      APP_DEBUG: ${APP_DEBUG:-false}
      APP_LOG_LEVEL: ${APP_LOG_LEVEL:-error}
      APP_URL: ${APP_URL:-http://invoiceshelf.test}
      DB_CONNECTION: ${DB_CONNECTION:-mysql}
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: ${DB_PORT:-3306}
      DB_DATABASE: ${DB_DATABASE:-invoiceshelf}
      DB_USERNAME: ${DB_USERNAME:-invoiceshelf}
      DB_PASSWORD: ${DB_PASSWORD}
      BROADCAST_DRIVER: ${BROADCAST_DRIVER:-log}
      CACHE_DRIVER: ${CACHE_DRIVER:-redis}
      QUEUE_DRIVER: ${QUEUE_DRIVER:-redis}
      SESSION_DRIVER: ${SESSION_DRIVER:-redis}
      SESSION_LIFETIME: ${SESSION_LIFETIME:-1440}
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PASSWORD: ${REDIS_PASSWORD:-null}
      REDIS_PORT: ${REDIS_PORT:-6379}
      MAIL_DRIVER: ${MAIL_DRIVER:-mailgun}
      MAILGUN_DOMAIN: ${MAILGUN_DOMAIN:-mg.srvxx.com}
      MAILGUN_SECRET: ${MAILGUN_SECRET}
      MAIL_HOST: ${MAIL_HOST:-smtp.mailgun.org}
      MAIL_PORT: ${MAIL_PORT:-587}
      MAIL_USERNAME: ${MAIL_USERNAME:-invoiceshelf@mg.srvxx.com}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_ENCRYPTION: ${MAIL_ENCRYPTION:-tls}
      PUSHER_APP_ID: ${PUSHER_APP_ID:-null}
      PUSHER_KEY: ${PUSHER_KEY:-null}
      PUSHER_SECRET: ${PUSHER_SECRET:-null}
      SANCTUM_STATEFUL_DOMAINS: ${SANCTUM_STATEFUL_DOMAINS:-invoiceshelf.test}
      SENTRY_LARAVEL_DSN: ${SENTRY_LARAVEL_DSN:-null}
      SESSION_DOMAIN: ${SESSION_DOMAIN:-invoiceshelf.test}
      TRUSTED_PROXIES: ${TRUSTED_PROXIES:-*}
    depends_on:
      - redis
      - db
